import { Job } from './job';

export const JOBS: Job[] = [
    { id: 1, name: 'Actuary', location: "Toronto, Ontario",
     description: "Actuaries analyze the financial costs of risk and uncertainty. They use mathematics, statistics, and financial theory to assess the risk of potential events, and they help businesses and clients develop policies that minimize the cost of that risk. Actuaries' work is essential to the insurance industry.",
    source: "https://www.bls.gov/ooh/math/actuaries.htm#:~:text=Actuaries%20analyze%20the%20financial%20costs,essential%20to%20the%20insurance%20industry.",
    modality: "Hybrid"},
    { id: 2, name: 'Accountant',location: "New York City, New York", 
    description: "An Accountant helps businesses make critical financial decisions by collecting, tracking, and correcting the company's finances. They are responsible for financial audits, reconciling bank statements, and ensuring financial records are accurate throughout the year.",
     source: "https://resources.workable.com/accountant-job-description#:~:text=An%20Accountant%20helps%20businesses%20make,are%20accurate%20throughout%20the%20year.",
     modality: "In-Person"},
    { id: 3, name: 'Analyst',location: "Philadelphia, Pennsylvania",
     description: "Serve as liaison between staff and management by analyzing and interpreting data for company procedures, policies, and workflows. Prepare, analyze, and summarize operational results for use by various key stakeholders, creating reports, specifications, instructions, and flowcharts.",
     source: "https://business.linkedin.com/talent-solutions/resources/how-to-hire-guides/analyst/job-description#:~:text=Serve%20as%20liaison%20between%20staff,%2C%20specifications%2C%20instructions%2C%20and%20flowcharts",
     modality: "Hybrid"},
    { id: 4, name: 'Data Engineer', location: "Boston, Massachusetts", 
    description: "Data engineers implement methods to improve data reliability and quality. They combine raw information from different sources to create consistent and machine-readable formats. They also develop and test architectures that enable data extraction and transformation for predictive or prescriptive modeling.",
    source: "https://resources.workable.com/data-engineer-job-description#:~:text=Data%20engineers%20implement%20methods%20to,for%20predictive%20or%20prescriptive%20modeling.",
    modality: "Remote"},
    { id: 5, name: 'Teacher',location: "Charlotte, North Carolina",
     description: "Develops, plans, and implements curriculum, lesson plans, and educational programs for student audiences within areas of expertise. Advises, tests, and teaches students audiences in a variety of academic subjects. Presents and reinforces learning concepts within a specified subject or subject area.",
     source: "https://jobdescriptions.unm.edu/detail.php?id=H0007#:~:text=Develops%2C%20plans%2C%20and%20implements%20curriculum,specified%20subject%20or%20subject%20area.",
     modality: "In-Person"},
    { id: 6, name: 'Teacher',location: "Villanova, Pennsylvania", 
    description: "Develops, plans, and implements curriculum, lesson plans, and educational programs for student audiences within areas of expertise. Advises, tests, and teaches students audiences in a variety of academic subjects. Presents and reinforces learning concepts within a specified subject or subject area.",
    source: "https://jobdescriptions.unm.edu/detail.php?id=H0007#:~:text=Develops%2C%20plans%2C%20and%20implements%20curriculum,specified%20subject%20or%20subject%20area.",
    modality: "In-Person"},
    { id: 7, name: 'Data Scientist', location: "Philadelphia, Pennsylvania",
     description: "A data scientist is an analytics professional who is responsible for collecting, analyzing and interpreting data to help drive decision-making in an organization.",
     source: "https://www.techtarget.com/searchenterpriseai/definition/data-scientist#:~:text=A%20data%20scientist%20is%20an,decision%2Dmaking%20in%20an%20organization.",
     modality: "Hybrid"},
    { id: 8, name: 'Audit Assistant',location: "New York City, New York",
     description: "Audit assistants prepare the financial reports and ensure compliance with the tax regulations. They determine both the strengths and weaknesses of the finances of an organization. Their job includes checking the accuracy of accounting procedures and systems.",
     source: "https://www.zippia.com/audit-assistant-jobs/what-does-an-audit-assistant-do/",
     modality: "In-Person"},
    { id: 9, name: 'Project Manager',location: "Cambridge, Massachusetts",
     description: "A project manager has to plan and develop the project idea. They need to create and lead the team, monitor project progress, set deadlines, solve issues that arise, manage money, ensure stakeholder satisfaction, and evaluate project performance, including the performance of their team members.",
     source: "https://www.simplilearn.com/project-manager-job-description-article#:~:text=A%20project%20manager%20has%20to,performance%20of%20their%20team%20members.",
     modality: "In-Person"},
    { id: 10, name: 'Computational Analyst', location: "Raleigh, North Carolina",
     description: "Analysts calculate requirements for how much memory, storage, and computing power the computer system needs. They prepare diagrams for programmers or engineers to use when building the system. Analysts also work with these people to solve problems that arise after the initial system setup.",
     source: "https://www.bls.gov/ooh/computer-and-information-technology/computer-systems-analysts.htm#:~:text=Analysts%20calculate%20requirements%20for%20how,after%20the%20initial%20system%20setup.",
     modality: "Remote"},
    { id: 11, name: 'Teacher',location: "Westchester, New York",
     description: "Develops, plans, and implements curriculum, lesson plans, and educational programs for student audiences within areas of expertise. Advises, tests, and teaches students audiences in a variety of academic subjects. Presents and reinforces learning concepts within a specified subject or subject area.",
     source: "https://jobdescriptions.unm.edu/detail.php?id=H0007#:~:text=Develops%2C%20plans%2C%20and%20implements%20curriculum,specified%20subject%20or%20subject%20area.",
     modality: "In-Person"},
    { id: 12, name: 'Improvement Specialist',location: "Chicago, Illinois", 
    description: "A Continuous Improvement Specialist analyzes a company's processes and makes suggestions on how to improve them, working with the Operations and Supply Chain teams in recognizing opportunities, making and implementing changes, and sustaining improvements.", 
    source: "https://scmtalent.com/continuous-improvement-specialist-job-description#:~:text=A%20Continuous%20Improvement%20Specialist%20analyzes,implementing%20changes%2C%20and%20sustaining%20improvements.",
    modality: "Hybrid"}

];